board review/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>', views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:id>/delete/', views.delete, name='delete'),
    path('<int:id>/edit/', views.edit, name='edit'),
    path('<int:id>/update/', views.update, name='update'),
]

board review/articles/views.py
from django.shortcuts import render, redirect
from .models import Article

# Create your views here.
def index(request):
    articles = Article.objects.all()

    context = {
        'articles': articles,
    }

    return render(request, 'index.html', context)


def detail(request, id):
    article = Article.objects.get(id=id)

    context = {
        'article': article,
    }

    return render(request, 'detail.html', context)


def new(request):
    return render(request, 'new.html')


def create(request):
    title = request.POST.get('title')
    content = request.POST.get('content')

    article = Article()
    article.title = title
    article.content = content
    article.save()
    return redirect('articles:detail', id=article.id)


def delete(request, id):
    article = Article.objects.get(id=id)
    article.delete()

    return redirect('articles:index')


def edit(request, id):
    article = Article.objects.get(id=id)

    context = {
        'article' : article,
    }
    
    return render(request, 'edit.html', context)


def update(request, id):
    # 새로운 정보
    title = request.POST.get('title')
    content = request.POST.get('content')

    # 기존 정보
    article = Article.objects.get(id=id)

    article.title = title
    article.content = content
    article.save()

    return redirect('articles:detail', id=article.id)

board review/articles/templates/detail.html
{% extends 'base.html' %}

{% block body %}
    <div class="card mt-3">
        <div class="card-header">
            {{ article.title }}
        </div>
        <div class="card-body">
            {{ article.content }}
        </div>
        <div class="card-footer">
            {{ article.created_at }}
            <a href="{% url 'articles:delete' id=article.id %}" class="btn btn-danger">delete</a>
            <a href="{% url 'articles:edit' id=article.id %}" class="btn btn-warning">edit</a>
        </div>
    </div>
{% endblock %}

board review/articles/templates/edit.html
{% extends 'base.html' %}

{% block body %}
    <form action="{% url 'articles:update' id=article.id %}" class="mt-4" method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label for="title" class="form-label">title</label>
            <input type="text" class="form-control" id="title" name="title" value="{{article.title}}">
        </div>

        <div class="mb-3">
            <label for="content" class="form-label">content</label>
            <textarea name="content" id="content" cols="30" rows="10" class="form-control">{{article.content}}</textarea>
        </div>

        <input type="submit" class="btn btn-primary">
    </form>

{% endblock %}

board review/articles/templates/index.html
{% extends 'base.html' %}

{% block body %}
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>title</th>
                <th>link</th>
            </tr>
        </thead>
        <tbody>
            {% for article in articles %}
            <tr>
                <td>{{ article.id }}</td>
                <td>{{ article.title }}</td>
                <td>
                    <a href="{% url 'articles:detail' id=article.id %}">detail</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

board review/articles/templates/new.html
{% extends 'base.html' %}

{% block body %}
    <form action="{% url 'articles:create' %}" class="mt-4" method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label for="title" class="form-label">title</label>
            <input type="text" class="form-control" id="title" name="title">
        </div>

        <div class="mb-3">
            <label for="content" class="form-label">content</label>
            <textarea name="content" id="content" cols="30" rows="10" class="form-control"></textarea>
        </div>

        <input type="submit" class="btn btn-primary">
    </form>

{% endblock %}

board review/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'articles:index' %}">Home</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'articles:new' %}">New</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" aria-disabled="true">Disabled</a>
              </li>
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
    </nav>
    <div class="container">
        {% block body %}

        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>