1-N review2/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'), 
    path('<int:id>', views.detail, name='detail'),
    path('<int:article_id>/comments/create/', views.comment_create, name='comment_create'),
    path('<int:article_id>/comments/<int:id>/delete/', views.comment_delete, name='comment_delete'),
]

1-N review2/board/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]

1-N review2/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()


class Comment(models.Model):
    content = models.TextField()
    article = models.ForeignKey(Article, on_delete=models.CASCADE)

1-N review2/articles/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = '__all__'


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('article', )

1-N review2/articles/views.py
from django.shortcuts import render, redirect
from .models import Article, Comment
from .forms import ArticleForm, CommentForm

# Create your views here.
def index(request):
    articles = Article.objects.all()
    context = {
        'articles': articles,
    }
    return render(request, 'index.html', context)


def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else :
        form = ArticleForm()
    context = {
        'form': form,
    }
    return render(request, 'form.html', context)


def detail(request, id):
    article = Article.objects.get(id=id)
    comment_form = CommentForm()
    context = {
        'article': article,
        'comment_form': comment_form
    }
    return render(request, 'detail.html', context)


def comment_create(request, article_id):
    article = Article.objects.get(id=article_id)
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.article = article
        comment.save()
        return redirect('articles:detail', id=article.id)
    

def comment_delete(request, article_id, id):
    comment = Comment.objects.get(id=id)
    comment.delete()
    return redirect('articles:detail', id=article_id)

1-N review2/articles/templates/detail.html
{% extends 'base.html' %}

{% block body %}
    <h3>{{ article.title }}</h3>
    <p>{{ article.content }}</p>
    <form action="{% url 'articles:comment_create' article_id=article.id %}" method="POST">
        {% csrf_token %}
        {{ comment_form }}
        <input type="submit">
    </form>
    {% for comment in article.comment_set.all %}
        <p>{{ comment.content }}</p>
        <a href="{% url 'articles:comment_delete' article_id=article.id id=comment.id %}">delete</a>
    {% endfor %}
{% endblock %}

1-N review2/articles/templates/form.html
{% extends 'base.html' %}

{% block body %}
    <form action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
{% endblock %}

1-N review2/articles/templates/index.html
{% extends 'base.html' %}
{% block body %}
<h1>index</h1>
<a href="{% url 'articles:create' %}">create</a>
    {% for article in articles %}
        <h3>{{ article.title }}</h3>
        <a href="{% url 'articles:detail' id=article.id %}">detail</a>
    {% endfor %}
{% endblock %}